---
- name: Generate Random Password
  set_fact:
    user_pass: "{{ pwd_alias }}"

- name: Create user "{{ systemuser }}"
  user:
    name: "{{ systemuser }}"
    comment: "{{ comments }}"
    append: false
    shell: /bin/bash
    password: "{{ user_pass | password_hash('sha512') }}"
    update_password: on_create
    state: present
  register: user_status

- name: Register user_status variable
  set_fact:
    task_changed: user_status.changed

- name: Set account never expiry
  shell: chage -I -1 -m 7 -M 90 -W 5 -E -1 "{{ systemuser }}"

- name: Copy sudoers configurations
  copy:
    src: sudoers_user
    dest: "/etc/sudoers.d/{{ systemuser }}"
    owner: root
    group: root
    mode: '0440'
    force: true
    validate: /usr/sbin/visudo -csf %s

- name: Retrive Password
  debug:
    msg: "Password for non-root user {{ systemuser }} - {{ user_pass }}"
  when: task_changed | bool


