---
- name: Generate Random Password
  set_fact:
    user_pass: "{{ pwd_alias }}"

- name: Create non-root user - "{{ nonrootuser }}"
  user:
    name: "{{ nonrootuser }}"
    comment: "{{ comments }}"
    append: false
    shell: /bin/bash
    password: "{{ user_pass | password_hash('sha512') }}"
    update_password: on_create
    state: present
  register: user_status

- name: Register user_status variable
  set_fact:
    task_changed: user_status.changed

- name: Set account and password expiry
  shell: chage -I -1 -m 7 -M 90 -W 5 -E -1 "{{ nonrootuser }}"

- name: Copy sudoers configurations
  copy:
    src: "{{ sudoers_user_file }}"
    dest: "/etc/sudoers.d/{{ nonrootuser }}"
    owner: root
    group: root
    mode: '0440'
    force: true
    validate: /usr/sbin/visudo -csf %s
  when: sudoers_user_file is defined

- name: Retrieve Password
  debug:
    msg: "Password for non-root user {{ nonrootuser }} - {{ user_pass }}"
  when: task_changed | bool


