---
- name: Generate Random Password
  set_fact:
    user_pass: "{{ pwd_alias }}"

- name: Create user "{{ systemuser }}"
  user:
    name: "{{ systemuser }}"
    comment: "{{ comments }}"
    append: false
    shell: /bin/bash
    password: "{{ user_pass | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: Register user_status variable
  set_fact:
    code_changed: user_status.changed

- name: Set account never expiry
  shell: cchage -I -1 -m 7 -M 90 -W 5 -E -1 "{{ systemuser }}"

- name: Retrive Password
  debug:
    msg: "Password for {{ systemuser }} - {{ user_pass }}"
  when: code_changed


