---
# tasks file for cyberark
- name: Add CyberArk service user1
  user:
    name: "{{ cyberuser1 }}"
    comment: "Privileged User for CyberArk"
    append: false
    group: users
    shell: /bin/bash
    update_password: on_create
    state: present
    password: "{{ cyberuser1 | password_hash('sha512') }}"

- name: Add CyberArk service user2
  user:
    name: "{{ cyberuser2 }}"
    comment: "Privileged User for CyberArk"
    append: false
    group: users
    shell: /bin/bash
    update_password: on_create
    state: present
    password: "{{ cyberuser2 | password_hash('sha512') }}"

- name: Setup permissions for CyberArk service user1
  lineinfile:
    path: "/etc/sudoers.d/{{ cyberuser1 }}"
    line: "{{ cybersudoers1 }}"
    mode: "0440"
    create: true
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: Setup permissions for CyberArk service user2
  lineinfile:
    path: "/etc/sudoers.d/{{ cyberuser2 }}"
    line: "{{ cybersudoers2 }}"
    mode: "0440"
    create: true
    state: present
    validate: /usr/sbin/visudo -cf %s

