---
# tasks file for uni-user
- name: "Add user for CMDB"
  user:
    name: "{{ cmdbuser }}"
    comment: "Privileged User for Servicenow CMDB"
    append: false
    shell: /bin/bash
    password: "{{ cmdbpass | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: Set account never expire
  shell: chage -I -1 -m 0 -M 99999 -E -1 "{{ cmdbuser }}"


- name: Copy cmdb sudoers configurations
  ansible.builtin.copy:
    src: sudoers_cmdb
    dest: /etc/sudoers.d/cmdb
    owner: root
    group: root
    mode: '0440'