---
- name: Generate Random Password
  set_fact:
    user_pass: "{{ pwd_alias }}"

- name: Create user "{{ systemuser }}"
  user:
    name: "{{ systemuser }}"
    comment: "{{ comments }}"
    append: false
    shell: /bin/bash
    password: "{{ user_pass | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: Set account never expiry
  shell: cchage -I -1 -m 7 -M 90 -W 5 -E -1 "{{ systemuser }}"

- name: Retrive Password
  debug:
    msg: "Password for {{ systemuser }} - {{ user_pass }}"

- name: "Delete sudoers file if exist"
  file:
   path: "/etc/sudoers.d/{{ systemuser }}"
   state: absent

- name: Set up password less auth
  lineinfile:
    path: "/etc/sudoers.d/{{ systemuser }}"
    line: "{{ systemuser }}{{ sudoers }}"
    mode: '0440'
    create: true
    state: present
    validate: /usr/sbin/visudo -cf %s
