---
# tasks file for cyberark
- name: Add Control-M service user
  user:
    name: "{{ cmuser }}"
    comment: "Control-M service user"
    append: false
    create_home: true
    shell: "/bin/bash"
    home: "/ctmagent"
    skeleton: "/ctmagent"
    update_password: on_create
    state: present
    password: "{{ cmpass | password_hash('sha512') }}"

- name: Setup permissions for CyberArk service user1
  lineinfile:
    path: "/etc/sudoers.d/{{ cyberuser1 }}"
    line: "{{ cybersudoers1 }}"
    mode: "0440"
    create: true
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: Setup permissions for CyberArk service user2
  lineinfile:
    path: "/etc/sudoers.d/{{ cyberuser2 }}"
    line: "{{ cybersudoers2 }}"
    mode: "0440"
    create: true
    state: present
    validate: /usr/sbin/visudo -cf %s

